### ISSUE TITLE
How to get it working on web?

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [LeGoffMael/video_editor#102]
Hello,
I see this is a great library and it works well on IOS and android, any idea on what's needed to make it work on the web? i can do some work with some guidance

Cheers

**Comment by LeGoffMael** [comment]
This library is using dart only to render the UI so there is no problem of web compatibility.

The issue is how to export the video, for this we are using `flutter_ffmpeg_kit`, so when this library will be compatible for web, `video_editor` will be as well. You can check the progress on this task there : https://github.com/tanersener/ffmpeg-kit/issues/4

**Comment by maRci002** [comment]
Check out #146 it is possible to do it.
