### ISSUE TITLE
On Android is EXTREMELY SLOW

### ISSUE THREAD

**Issue by carrasc0** [LeGoffMael/video_editor#171]

**Comment by LeGoffMael** [comment]
Since the v3.0.0 the exportation process is not handled by this package itself. It only provides a quick commands to run with ffmpeg. Please reopen an issue or a PR if you think the `VideoFFmpegVideoEditorConfig` class should be updated.

Maybe you should look into ffmpeg documentation on ways to increase the exportation speed or uses other methods (your own backend for example)
