### ISSUE TITLE
Play button not working

### ISSUE THREAD

**Issue by umer322** [LeGoffMael/video_editor#8]
The play button isn't working on CropGridViewer with you pass showGrid = null to preview video.I have to tap on video screen to play video but video doesn't play when i press play button

**Comment by seel-channel** [comment]
showGrid is a boolean argument, then it's not recommend pass null. If don't want to showGrid you do `show the grid: false`.

Also, the play button is outside the CropGrodViewer at example.dart and I think didn't add play and pause because I forgot it. You can add the play and pause functionality with the icon. Like this

```dart
GestureDetector(
   onTap: () async {
       final video = controller.videoController;
       if (video.isPlaying) await video.pause();
       else await video.play();
   },
   child: Icon(...),
)
```
